---
title: Host-specificity and core taxa of seagrass leaf microbiome identified across
  tissue age and geographical regions 
  | *Sanders-Smith, R. & Segovia, B.T.*(*joint contribution*), Forbes, C., Hessing-Lewis, M., Morien, E., Lemay, M.A., O'Connor, M. I., Parfrey, L.W.
author: "Bianca Trevizan Segovia"
date: "20/11/2020"
output:
  pdf_document:
    latex_engine: xelatex
  html_document: default
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Table S4 #
```{r, warning=FALSE,message=FALSE}
### load packages ###
library(tidyverse)
library(reshape2)
library(dplyr)
library(stats)
library(ggplot2)
library(ggthemes)
library(Biostrings)
library(phyloseq)

### disabling scientific notation ###
options(scipen = 999)
```

## save Indval Table statistics for Table S4 ##

```{r}

### importing master table ###
All_multipatt <- read.csv("data/IndVal_taxonomy_relat_abund.csv", header=T)
colnames(All_multipatt)

### melting: rearrange data from wider to longer ###
All_multipatt_melt.RA <- melt(All_multipatt, id.vars = "OTU", 
                              measure.vars = c("artificial.choked",
                                               "seawater.choked",
                                               "seawater.goose",
                                               "seawater.mcmullin",
                                               "seawater.triquet",
                                               "zostera_new.choked",
                                               "zostera_new.goose",
                                               "zostera_new.mcmullin",
                                               "zostera_new.triquet",
                                               "zostera_old.choked",
                                               "zostera_old.goose",
                                               "zostera_old.mcmullin",
                                               "zostera_old.triquet")) 

### melt automatically assigns column names variable and value ###
### change column names here ###
All_multipatt_melt.RA <- All_multipatt_melt.RA %>% 
  dplyr::rename(relat_abund_host_region = variable, Abundance= value)

### add back the metadata and taxonomy info ###
All_multipatt_melt.RA$Rank4 <- All_multipatt$Rank4
All_multipatt_melt.RA$Rank5 <- All_multipatt$Rank5
All_multipatt_melt.RA$Rank6 <- All_multipatt$Rank6
All_multipatt_melt.RA$Rank7 <- All_multipatt$Rank7

### add back indval info while renaming indval_group to Core and stat to Indval ###
All_multipatt_melt.RA$Core <- All_multipatt$indval_group
All_multipatt_melt.RA$Indval <- All_multipatt$indval.stat
All_multipatt_melt.RA$p.value <- All_multipatt$p.value


### create column with only Host labels from the relat_abund_host_region column ###
### case_when and grepl allow to transform:
### i.e. the labels that have "new" in it, in the relat_abund_host_region column, into ~ "New leaf" ###
All_multipatt_melt.RA <- All_multipatt_melt.RA %>%
  dplyr::mutate(Host = case_when(grepl("new", relat_abund_host_region) ~ "New leaf",
                           grepl("old", relat_abund_host_region) ~ "Old leaf",
                           grepl("seawater", relat_abund_host_region) ~ "Seawater",
                           grepl("artificial", relat_abund_host_region) ~ "Artificial"))

### create new column with only Region labels from the relat_abund_host_region column ###
All_multipatt_melt.RA <- All_multipatt_melt.RA %>%
  dplyr::mutate(Region = case_when(grepl("choked", relat_abund_host_region) ~ "Choked",
                          grepl("triquet", relat_abund_host_region) ~ "Triquet",
                          grepl("goose", relat_abund_host_region) ~ "Goose",
                          grepl("mcmullin", relat_abund_host_region) ~ "McMullin"))

All_multipatt_melt.RA$OTU <- as.character(All_multipatt$OTU)
All_multipatt_melt.RA$A.specificity. <- as.character(All_multipatt$A.specificity.)
All_multipatt_melt.RA$B.fidelity. <- as.character(All_multipatt$B.fidelity.)
All_multipatt_melt.RA$Region <- as.character(All_multipatt_melt.RA$Region)
All_multipatt_melt.RA$Core <- as.character(All_multipatt_melt.RA$Core)
All_multipatt_melt.RA$Host <- as.character(All_multipatt_melt.RA$Host)

### filter indval stats higher than 0.7 ###
All_multipatt_melt.RA <- dplyr::filter(All_multipatt_melt.RA, Indval > 0.7)

### filter prevalence to over 50% 
### (taxa are present in over 50% of the samples from each indval group) ###
All_multipatt_melt.RA <- dplyr::filter(All_multipatt_melt.RA, B.fidelity. > 0.5)

### filter for the indval_groups I am interested in ###
All_multipatt_melt.RA.subset <- dplyr::filter(All_multipatt_melt.RA,
                                              Core == "zostera_new" | 
                                                Core == "zostera_old" | 
                                                Core == "zostera_new+zostera_old" | 
                                                Core == "seawater" | 
                                                Core == "artificial"| 
                                                Core == "artificial+zostera_old")

### create column Core2 with labels for the final graph: this will be the Y-axis of the bubble plot ###
All_multipatt_melt.RA.subset <- All_multipatt_melt.RA.subset %>% 
  dplyr::mutate(Core2 = dplyr::recode(Core, 
                              "artificial" = "Artificial Core",
                              "seawater" = "Seawater Core",
                              "zostera_new" = "New leaf Core",
                              "zostera_old" = "Old leaf Core",
                              "zostera_new+zostera_old" = "Z. marina Core",
                              "artificial+zostera_old" = "Marine Surfaces Core"))

### create object containing the order of the indval group I want to appear in the y-axis ###
x <- c("Z. marina Core","New leaf Core",
       "Old leaf Core","Seawater Core", 
       "Artificial Core", "Marine Surfaces Core")
### arrange column according to the order established in x object ###
All_multipatt_melt.RA.subset <- All_multipatt_melt.RA.subset %>%
  dplyr::mutate(Core2 =  factor(Core2, levels = x)) %>%
  dplyr::arrange(Core2)

### create column with lowest taxonomy level IDed ###
All_multipatt_melt.RA.subset$lowest_tax_level <- paste(All_multipatt_melt.RA.subset$Rank5,
All_multipatt_melt.RA.subset$Rank6,"_", 
All_multipatt_melt.RA.subset$OTU, sep="")

### remove underlines from lowest_tax_level Rank5 labels ###
### remove first 2 characters and replace with nothing ###
All_multipatt_melt.RA.subset$lowest_tax_level <- gsub("^.{0,2}", 
                                                      "",
All_multipatt_melt.RA.subset$lowest_tax_level)

## Refine labels ##
### relabel some of the taxa: ###
### add species level where we have it, 
### fix some labels for order where family is not available
All_multipatt_melt.RA.subset <- All_multipatt_melt.RA.subset %>% 
  dplyr::mutate(lowest_tax_level2 = dplyr::recode(lowest_tax_level,
                                          "Oceanospirillaceae__Marinomonas_30173" = "Oceanospirillaceae__Marinomonas posidonica IVIA.Po.181_30173",
                                          "Oceanospirillaceae__Marinomonas_48134" = "Oceanospirillaceae__Marinomonas posidonica IVIA.Po.181_48134",
                                          "Flavobacteriaceae__Tenacibaculum_35344" = "Flavobacteriaceae__Tenacibaculum lutimaris_35344",
                                          "Sva0996_marine_group__Sva0996_marine_group_37101" = "Acidimicrobiales__Sva0996 marine group_37101",
                                          "LWSR.14__LWSR.14_27699" =  "Rickettsiales_LWSR.14_27699",
                                          "uncultured__uncultured_14831" = "Acidimicrobiales__uncultured_14831",
                                          "uncultured__uncultured_14827" = "Acidimicrobiales__uncultured_14827",
                                          "Piscirickettsiaceae__Marine_Methylotrophic_Group_3_40696" = "Piscirickettsiaceae__Marine Methylotrophic Group 3_40696",
                                          "Piscirickettsiaceae__Marine_Methylotrophic_Group_3_18005" = "Piscirickettsiaceae__Marine Methylotrophic Group 3_18005",
                                          "Piscirickettsiaceae__Marine_Methylotrophic_Group_3_18003" = "Piscirickettsiaceae__Marine Methylotrophic Group 3_18003",
                                          "Piscirickettsiaceae__Marine_Methylotrophic_Group_3_18006" = "Piscirickettsiaceae__Marine Methylotrophic Group 3_18006",
                                          "Piscirickettsiaceae__Marine_Methylotrophic_Group_3_2701" = "Piscirickettsiaceae__Marine Methylotrophic Group 3_2701",
                                          "Simkaniaceae__Candidatus_Fritschea_892" = "Simkaniaceae __Candidatus Fritschea_892",
                                          "Flavobacteriaceae__Polaribacter_3_52079" = "Flavobacteriaceae__Polaribacter 3_52079",
                                          "Halieaceae__OM60(NOR5)_clade_44023" = "Halieaceae__OM60(NOR5) clade_44023",
                                          "Flavobacteriaceae__NS5_marine_group_17409" = "Flavobacteriaceae __NS5 marine group_17409",
                                          "Flammeovirgaceae__Candidatus_Amoebophilus_17904" = "Flammeovirgaceae__Candidatus Amoebophilus_17904",
                                        
                                          "JTB255_marine_benthic_group__JTB255_marine_benthic_group_41483" = "Xanthomonadales_JTB255 marine benthic group_41483",
                                          "OCS116_clade__OCS116_clade_34534" = "Rhizobiales_OCS116 clade_34534",
                                          "FamilyI_FamilyI_20142" = "Cyanobacteria_SubsectionI FamilyI_20142",
                                          "Planctomycetaceae__Pir4_lineage_22023" = "Planctomycetaceae__Pir4 lineage_22023",
                                          "uncultured_uncultured_44981" = "Sphingobacteriales_uncultured_44981",
                                          "OM190_OM190_41159" = "Planctomycetes_OM190_41159",
                                          "NS9_marine_group__NS9_marine_group_47474" = "Flavobacteriales_NS9 marine group_47474",
                                          "RhodobacteraceaeNA_32551" = "Rhodobacteraceae_uncultured_32551",
                                          "RhodobacteraceaeNA_18668" = "Rhodobacteraceae_uncultured_18668",
                                          "NS9_marine_group__NS9_marine_group_17952" = "Flavobacteriales_NS9 marine group_17952",
                                          "Methylophilaceae__OM43_clade_30773" = "Methylophilaceae__OM43 clade_30773",
                                          "Flavobacteriaceae__NS5_marine_group_33603" = "Flavobacteriaceae__NS5 marine group_33603",
                                          "OM1_clade__Candidatus_Actinomarina_3452" = "Acidimicrobiales_Candidatus Actinomarina_3452",
                                          "Porticoccaceae__SAR92_clade_17098" = "Porticoccaceae__SAR92 clade_17098",
                                          "FamilyI__Synechococcus_29876" = "Cyanobacteria_Synechococcus_29876",
                                          "Flavobacteriaceae__NS3a_marine_group_35569" = "Flavobacteriaceae__NS3a marine group_35569",
                                          "FamilyI__Synechococcus_15906" = "Cyanobacteria_Synechococcus_15906",
                                          "SAR86_clade__SAR86_clade_40537" = "Oceanospirillales_SAR86 clade_40537",
                                          "Flavobacteriaceae__NS4_marine_group_2487" = "Flavobacteriaceae__NS4 marine group_2487",
                                          "Porticoccaceae__SAR92_clade_17017" = "Porticoccaceae__SAR92 clade_17017",
                                          "FlavobacteriaceaeNA_35513" = "Flavobacteriaceae_uncultured_35513",
                                          "Flavobacteriaceae__NS5_marine_group_17553" = "Flavobacteriaceae__NS5 marine group_17553",
                                          
                                          
                                          "Surface_1__Surface_1_45078" = "Alphaproteobacteria_SAR11 clade_45078",
                                          "Flavobacteriaceae__NS4_marine_group_46779" = "Flavobacteriaceae__NS4 marine group_46779",
                                          "Microbacteriaceae__Candidatus_Aquiluna_48034" = "Microbacteriaceae__Candidatus Aquiluna_48034",
                                          "Flavobacteriaceae__NS4_marine_group_40661" = "Flavobacteriaceae__NS4 marine group_40661",
                                          "Flavobacteriaceae__NS5_marine_group_33608" = "Flavobacteriaceae__NS5 marine group_33608",
                                          "FamilyI__Synechococcus_15943" = "Cyanobacteria_Synechococcus_15943",
                                          "Flavobacteriaceae__NS5_marine_group_40600" = "Flavobacteriaceae__NS5 marine group_40600",
                                          "Microbacteriaceae__Candidatus_Aquiluna_35850" = "Microbacteriaceae__Candidatus Aquiluna_35850",
                                          "Flavobacteriaceae__NS5_marine_group_50346" = "Flavobacteriaceae__NS5 marine group_50346",
                                          "Flavobacteriaceae__NS5_marine_group_17554" = "Flavobacteriaceae__NS5 marine group_17554",
                                          "FamilyI__Synechococcus_15989" = "Cyanobacteria_Synechococcus_15989",
                                          "Surface_1__Surface_1_45026" = "Alphaproteobacteria_SAR11 clade_45026",
                                         
                                         
                                          "NS9_marine_group__NS9_marine_group_17960" = "Flavobacteriales_NS9 marine group_17960",
                                          "Microbacteriaceae__Candidatus_Aquiluna_48033" = "Microbacteriaceae__Candidatus Aquiluna_48033",
                                          "FamilyI__Synechococcus_15949" = "Cyanobacteria_Synechococcus_15949",
                                          "Flavobacteriaceae__NS5_marine_group_40601" = "Flavobacteriaceae__NS5 marine group_40601",
                                         
                                          "RhodobacteraceaeNA_49779" = "Rhodobacteraceae_uncultured_49779",
                                          "Flavobacteriaceae__NS5_marine_group_33607" = "Flavobacteriaceae__NS5 marine group_33607",
                                          "PS1_clade__PS1_clade_46021" = "Rhizobiales_PS1 clade_46021",
                                          "Flavobacteriaceae__NS5_marine_group_50345" = "Flavobacteriaceae__NS5 marine group_50345",
                                          "NS9_marine_group__NS9_marine_group_2296" = "Flavobacteriales_NS9 marine group_2296",
                                          "PS1_clade__PS1_clade_46024" = "Rhizobiales_PS1 clade_46024",
                                          "Surface_2__Surface_2_44082" = "Alphaproteobacteria_SAR11 clade_44082",
                                          "Halieaceae__OM60(NOR5)_clade_44024" = "Halieaceae__OM60(NOR5) clade_44024",
                                          "Porticoccaceae__SAR92_clade_17016" = "Porticoccaceae__SAR92 clade_17016",
                                          "Flavobacteriaceae__NS4_marine_group_46780" = "Flavobacteriaceae__NS4 marine group_46780",
                                          "Flavobacteriaceae__NS5_marine_group_40637" = "Flavobacteriaceae__NS5 marine group_40637",
                                          "Flavobacteriaceae__NS2b_marine_group_43365" = "Flavobacteriaceae__NS2b marine group_43365",
                                          "Flavobacteriaceae__NS5_marine_group_40640" = "Flavobacteriaceae__NS5 marine group_40640",
                                          "Flavobacteriaceae__NS4_marine_group_17607" = "Flavobacteriaceae__NS4 marine group_17607",
                                          "SAR116_clade_SAR116_clade_38203" = "Rickettsiales_SAR116 clade_38203",
                                          "FlavobacteriaceaeNA_35415" = "Flavobacteriaceae_uncultured_35415",
                                          "uncultured__uncultured_6439" = "Sphingobacteriales_uncultured_6439",
                                          "Flavobacteriaceae__NS5_marine_group_27262" = "Flavobacteriaceae__NS5 marine group_27262",
                                          "Spongiibacteraceae__BD1.7_clade_24610" = "Spongiibacteraceae__BD1.7 clade_24610",
                                          "Porticoccaceae__SAR92_clade_17015" = "Porticoccaceae__SAR92 clade_17015",
                                          "FlavobacteriaceaeNA_51493" = "Flavobacteriaceae_uncultured_51493",
                                          "KI89A_clade__KI89A_clade_16955" = "Gammaproteobacteria_KI89A clade_16955",
                                          "Flavobacteriaceae__NS5_marine_group_17410" = "Flavobacteriaceae__NS5 marine group_17410",
                                          "SAR86_clade__SAR86_clade_30104" = "Oceanospirillales_SAR86 clade_30104",
                                          "SAR116_clade__SAR116_clade_30265" = "Rickettsiales_SAR116 clade_30265",
                                          "Flavobacteriaceae__NS5_marine_group_27264" = "Flavobacteriaceae__NS5 marine group_27264",
                                          "SAR86_clade__SAR86_clade_30105" = "Oceanospirillales_SAR86 clade_30105",
                                          "Porticoccaceae__SAR92_clade_17099" = "Porticoccaceae__SAR92 clade_17099",
                                          "Flavobacteriaceae__NS5_marine_group_17455" = "Flavobacteriaceae__NS5 marine group_17455",
                                          "NS11.12_marine_group__NS11.12_marine_group_18042" = "Sphingobacteriales_NS11.12 marine group_18042",
                                          "E01.9C.26_marine_group__E01.9C.26_marine_group_39482" = "Gammaproteobacteria_E01.9C.26 marine group_39482",
                                          "Flavobacteriaceae__NS5_marine_group_27263" = "Flavobacteriaceae__NS5 marine group_27263",
                                          "Halieaceae__OM60(NOR5)_clade_25329" = "Halieaceae__OM60(NOR5) clade_25329",
                                          "Flavobacteriaceae__NS4_marine_group_40660" = "Flavobacteriaceae__NS4 marine group_40660",
                                          "Unknown_Family__uncultured_22898" = "Gammaproteobacteria Incertae Sedis_uncultured_22898",
                                          "FamilyI__Synechococcus_29875" = "Cyanobacteria_Synechococcus_29875",
                                          "Bdellovibrionaceae__OM27_clade_33887" = "Bdellovibrionaceae__OM27 clade_33887",
                                          "PS1_clade__PS1_clade_4919" = "Rhizobiales_PS1 clade_4919",
                                          "Comamonadaceae__BAL58_marine_group_39554" = "Comamonadaceae__BAL58 marine group_39554",
                                          "Surface_1__Surface_1_29349" = "Alphaproteobacteria_SAR11 clade_29349",
                                          "Surface_1__Surface_1_29343" = "Alphaproteobacteria_SAR11 clade_29343",
                                          "SAR116_clade__SAR116_clade_30267" = "Rickettsiales_SAR116 clade_30267",
                                          "Halieaceae__OM60(NOR5)_clade_7879" = "Halieaceae__OM60(NOR5) clade_7879",
                                          "FamilyI__Synechococcus_15910" = "Cyanobacteria_Synechococcus_15910",
                                          "Surface_2__Surface_2_44081" = "Alphaproteobacteria_SAR11 clade_44081",
                                          "FamilyI__Synechococcus_29877" = "Cyanobacteria_Synechococcus_29877",
                                          "DEV007__DEV007_41701" = "Verrucomicrobiales_DEV007_41701",
                                          "EctothiorhodospiraceaeNA_38096" = "Ectothiorhodospiraceae_uncultured_ 38096",
                                          "Sva0996_marine_group__Sva0996_marine_group_48418" = "Acidimicrobiales_Sva0996 marine group_48418",
                                          "Unknown_Family__uncultured_38396" = "Gammaproteobacteria Incertae Sedis_uncultured_38396",
                                          "[Caedibacter]_caryophilus_group__[Caedibacter]_caryophilus_group_37874" = "Rickettsiales_[Caedibacter] caryophilus group_37874",
                                          "Acidimicrobiaceae__Ilumatobacter_37052" = "Acidimicrobiaceae_Ilumatobacter nonamiensis YM16.303_37052",
                                          "NS11.12_marine_group__NS11.12_marine_group_18293" = "Sphingobacteriales_NS11.12 marine group_18293",
                                          "Sva0996_marine_group__Sva0996_marine_group_37104" = "Acidimicrobiales_Sva0996 marine group_37104",
                                          "LWSR−14__LWSR−14_27699" = "Rickettsiales_LWSR−14_27699",
                                          "DEV007__DEV007_21341" = "Verrucomicrobiales_DEV007_21341",
                                          "KI89A_clade__KI89A_clade_36555" = "Gammaproteobacteria_KI89A clade_36555",
                                          "LWSR.14__LWSR.14_27698" = "Rickettsiales_LWSR.14_27698",
                                          "NA_19759" = "Chromatiales_uncultured_19759",
                                          "Sva0996_marine_group__Sva0996_marine_group_48494" = "Acidimicrobiales_Sva0996 marine group_48494",
                                          "NS9_marine_group__NS9_marine_group_34991" = "Flavobacteriales_NS9 marine group_34991",
                                          "FlavobacteriaceaeNA_17637" = "Flavobacteriaceae_uncultured_17637",
                                          "NS11.12_marine_group__NS11.12_marine_group_18292" = "Sphingobacteriales_NS11.12 marine group_18292",
                                          "uncultured__uncultured_27953" = "Sphingobacteriales_uncultured_27953",
                                          "Sva0996_marine_group__Sva0996_marine_group_48419" = "Acidimicrobiales_Sva0996 marine group_48419",
                                          "RhodobacteraceaeNA_18614" = "Rhodobacteraceae_uncultured_18614",
                                          "DEV007__DEV007_41600" = "Verrucomicrobiales_DEV007_41600",
                                          "Bdellovibrionaceae__OM27_clade_33694" = "Bdellovibrionaceae__OM27 clade_33694",
                                          "Sva0996_marine_group__Sva0996_marine_group_37083" = "Acidimicrobiales_Sva0996 marine group_37083",
                                          "SR1_(Absconditabacteria)__SR1_(Absconditabacteria)_1686" = "SR1 (Absconditabacteria)_uncultured_1686",
                                          "SaprospiraceaeNA_31206" = "Saprospiraceae_uncultured_31206",
                                          "BacteriovoracaceaeNA_38025" = "Bacteriovoracaceae_uncultured_38025",
                                          "uncultured__uncultured_43340" = "Alphaproteobacteria Incertae Sedis_uncultured_43340",
                                          "Acidimicrobiaceae__Ilumatobacter_37054" = "Acidimicrobiaceae_Ilumatobacter nonamiensis YM16.303_37054",
                                          "FlavobacteriaceaeNA_43497" = "Flavobacteriaceae_uncultured_43497",
                                          "SR1_(Absconditabacteria)__SR1_(Absconditabacteria)_16876" = "SR1 (Absconditabacteria)_uncultured_16876",
                                          "NS11.12_marine_group__NS11.12_marine_group_18196" = "Sphingobacteriales_NS11.12 marine group_18196",
                                          "SaprospiraceaeNA_264" = "Saprospiraceae_uncultured_264",
                                          "Candidatus_Campbellbacteria__Candidatus_Campbellbacteria_8554" = "Parcubacteria_Candidatus Campbellbacteria_8554",
                                          "NS9_marine_group__NS9_marine_group_47478" = "Flavobacteriales_NS9 marine group_47478",
                                          "SR1_(Absconditabacteria)__SR1_(Absconditabacteria)_16877" = "SR1 (Absconditabacteria)_uncultured_16877",
                                          "Unknown_Family__uncultured_4229" = "Gammaproteobacteria Incertae Sedis_uncultured_4229",
                                          "KI89A_clade__KI89A_clade_36557" = "Gammaproteobacteria_KI89A clade_36557",
                                          "NS9_marine_group__NS9_marine_group_47476" = "Flavobacteriales_NS9 marine group_47476",
                                          "SR1_(Absconditabacteria)__SR1_(Absconditabacteria)_1676" = "SR1_(Absconditabacteria)_uncultured_1676",
                                          "Blfdi19__Blfdi19_12501" = "Myxococcales_Blfdi19_12501",
                                          "uncultured__uncultured_28102" = "Alphaproteobacteria Incertae Sedis_uncultured_28102",
                                          "Sva0996_marine_group__Sva0996_marine_group_37084" = "Acidimicrobiales_Sva0996 marine group_37084",
                                          "RhodobacteraceaeNA_49050" = "Rhodobacteraceae_uncultured_49050",
                                          "Sva0996_marine_group__Sva0996_marine_group_48492" = "Acidimicrobiales_Sva0996 marine group_48492",
                                          "Sva0996_marine_group__Sva0996_marine_group_36981" = "Acidimicrobiales_Sva0996 marine group_36981",
                                          "KI89A_clade__KI89A_clade_36558" = "Gammaproteobacteria_KI89A clade_36558",
                                          "OM190__OM190_41199" = "Planctomycetes_OM190_41199",
                                          "MD3.55__MD3.55_8538" = "Rickettsiales_MD3.55_8538",
                                          "DEV007__DEV007_21339" = "Verrucomicrobiales_DEV007_21339",
                                          "SaprospiraceaeNA_31073" = "Saprospiraceae_uncultured_31073",
                                          "RhodobacteraceaeNA_51778" = "Rhodobacteraceae_uncultured_51778",
                                          "KI89A_clade__KI89A_clade_13114" = "Gammaproteobacteria_KI89A clade_13114",
                                          "DEV007__DEV007_5336" = "Verrucomicrobiales_DEV007_5336",
                                          "RhodobacteraceaeNA_51853" = "Rhodobacteraceae_uncultured_51853",
                                          "uncultured__uncultured_44983" = "Sphingobacteriales_uncultured_44983",
                                          "FamilyI__Phormidium_25998" = "Cyanobacteria_Phormidium_25998",
                                          "PhyllobacteriaceaeNA_18789" = "Phyllobacteriaceae_uncultured_18789",
                                          "uncultured__uncultured_39291" = "Alphaproteobacteria Incertae Sedis_uncultured_39291",
                                          "OM190__OM190_3822" = "Planctomycetes_OM190_3822",
                                          "OM190__OM190_41206" = "Planctomycetes_OM190_41206",
                                          
                                          "OM190__OM190_41159" = "Planctomycetes_OM190_41159",
                                          "NS11−12_marine_group__NS11−12_marine_group_18201" = "Sphingobacteriales_NS11.12 marine group_18201",
                                          "Flavobacteriaceae__Polaribacter_1_35413" = "Flavobacteriaceae__Polaribacter 1_35413",
                                          "Rhodobacteraceae__Roseobacter_clade_NAC11.7_lineage_31818" = "Rhodobacteraceae__Roseobacter clade NAC11.7 lineage_31818",
                                          "Methylophilaceae__OM43_clade_30774" = "Methylophilaceae__OM43 clade_30774",
                                          "Rhodobacteraceae__Roseobacter_clade_NAC11−7_lineage_10635" = "Rhodobacteraceae__Roseobacter clade NAC11.7 lineage_10635",
                                          "Spongiibacteraceae__BD1.7_clade_24991" = "Spongiibacteraceae_BD1.7 clade_24991",
                                          "Simkaniaceae__Candidatus_Fritschea_13330" = "Simkaniaceae__Candidatus Fritschea_13330",
                                          "NS11.12_marine_group__NS11.12_marine_group_18201" = "Sphingobacteriales_NS11.12 marine group_18201",
                                          "NS9_marine_group__NS9_marine_group_17743" = "Flavobacteriales_NS9 marine group_17743",
                                          "NS11.12_marine_group__NS11.12_marine_group_18199" = "Sphingobacteriales_NS11.12 marine group_18199",
                                          "JL.ETNP.Y6__JL.ETNP.Y6_47274" = "Oceanospirillales_JL.ETNP.Y6_47274",
                                          "FamilyI__FamilyI_20142" = "Cyanobacteria_FamilyI_20142",
                                          "SAR116_clade__SAR116_clade_12953" = "Rickettsiales_SAR116 clade_12953",
                                          "SAR116_clade__SAR116_clade_38203" = "Rickettsiales_SAR116 clade_38203",
                                          "Porticoccaceae__SAR92_clade_17018" = "Porticoccaceae__SAR92 clade_17018"
  ))

### remove double-underlines and spaces from labels ###
All_multipatt_melt.RA.subset$lowest_tax_level2 <- gsub("__", "_",
All_multipatt_melt.RA.subset$lowest_tax_level2)

### create an object with top 10 core taxa of each sample type ###
OTUs_top_10 <- c("Methylophilaceae__Methylotenera_45266",
                  "Methylophilaceae__Methylotenera_45304",
                  "Rhodobacteraceae__uncultured_32477",
                  "Methylophilaceae__Methylotenera_51108",
                  "Methylophilaceae__Methylotenera_29491",
                  "Methylophilaceae__Methylotenera_45135",
                  "Alteromonadaceae__Paraglaciecola_3808",
                  "Oceanospirillaceae__Marinomonas_48192",
                  "Methylophilaceae__Methylotenera_45179",
                  "Alteromonadaceae__Alteromonas_25375",
                  "Saprospiraceae__Rubidimonas_39641",
                  "Piscirickettsiaceae__Marine_Methylotrophic_Group_3_40696",
                  "Rhizobiaceae__Rhizobium_19725",
                  "Oceanospirillaceae__Marinomonas_30173",
                  "Piscirickettsiaceae__uncultured_42467",
                  "Piscirickettsiaceae__uncultured_42432",
                  "Oceanospirillaceae__Marinomonas_48134",
                  "Piscirickettsiaceae__Marine_Methylotrophic_Group_3_18005",
                  "Methylophilaceae__Methylotenera_29493",
                  "Methylophilaceae__Methylotenera_29578",
                  "Piscirickettsiaceae__Marine_Methylotrophic_Group_3_18003",
                  "Granulosicoccaceae__Granulosicoccus_15155",
                  "Alteromonadaceae__Glaciecola_7867",
                  "Granulosicoccaceae__Granulosicoccus_46431",
                  "Rhodobacteraceae__Octadecabacter_40749",
                  "Spongiibacteraceae__BD1.7_clade_24991",
                  "Halieaceae__Pseudohaliea_25282",
                  "Granulosicoccaceae__Granulosicoccus_15168",
                  "Simkaniaceae__Candidatus_Fritschea_892",
                  "Planctomycetaceae__Blastopirellula_22112",
                  "Saprospiraceae__Lewinella_33348",
                  "Flavobacteriaceae__Ulvibacter_24786",
                  "Flavobacteriaceae__Polaribacter_3_52079",
                  "Halieaceae__OM60(NOR5)_clade_44023",
                  "Flavobacteriaceae__NS5_marine_group_17409",
                  "Flavobacteriaceae__Tenacibaculum_35344",
                  "Rhodobacteraceae__Ascidiaceihabitans_31970",
                  "Halieaceae__Luminiphilus_7857",
                  "Cryomorphaceae__uncultured_34172",
                  "Flavobacteriaceae__Formosa_43620",
                  "Flavobacteriaceae__Flavicella_27016",
                  "Saprospiraceae__uncultured_2307",
                  "Thiotrichaceae__Cocleimonas_45935",
                  "Thiotrichaceae__Cocleimonas_32070",
                  "Oceanospirillaceae__Oleibacter_36424",
                  "Flammeovirgaceae__Candidatus_Amoebophilus_17904",
                  "Sva0996_marine_group__Sva0996_marine_group_37101",
                  "Rhodobacteraceae__uncultured_37802",
                  "Thiotrichaceae__Cocleimonas_32145",
                  "LWSR.14__LWSR.14_27699",
                  "Aeromonadaceae__uncultured_43869",
                  "Thiotrichaceae__Cocleimonas_51144",
                  "Saprospiraceae__uncultured_44888",
                  "uncultured__uncultured_14831",
                  "uncultured__uncultured_14827",
                  "Flavobacteriaceae__Maribacter_47051",
                  "Saprospiraceae__Rubidimonas_39402",
                  "Saprospiraceae__Lewinella_10383",
                  "Erythrobacteraceae__Erythrobacter_415",
                  "Granulosicoccaceae__Granulosicoccus_49894",
                  "Granulosicoccaceae__Granulosicoccus_49861")

multipatt_top_10 <- All_multipatt_melt.RA.subset %>% 
  dplyr::filter(lowest_tax_level %in% OTUs_top_10 )

### relabel some of the taxa: 
### add species level where we have it, 
### fix some labels for order where family is not available ###
multipatt_top_10 <- multipatt_top_10 %>% 
  dplyr::mutate(lowest_tax_level2= dplyr::recode(lowest_tax_level,
                                         "Oceanospirillaceae__Marinomonas_30173" = "Oceanospirillaceae__Marinomonas posidonica IVIA-Po-181_30173",
                                         "Oceanospirillaceae__Marinomonas_48134" = "Oceanospirillaceae__Marinomonas posidonica IVIA-Po-181_48134",
                                         "Flavobacteriaceae__Tenacibaculum_35344" = "Flavobacteriaceae__Tenacibaculum lutimaris_35344",
                                         "Sva0996_marine_group__Sva0996_marine_group_37101" = "Acidimicrobiales__Sva0996 marine group_37101",
                                         "LWSR.14__LWSR.14_27699" =  "Rickettsiales__LWSR.14_27699",
                                         "uncultured__uncultured_14831" = "Acidimicrobiales__uncultured_14831",
                                         "unculture__uncultured_14827" = "Acidimicrobiales__uncultured_14827",
                                         "Piscirickettsiaceae__Marine_Methylotrophic_Group_3_40696" = "Piscirickettsiaceae__Marine Methylotrophic Group 3_40696",
                                         "Piscirickettsiaceae__Marine_Methylotrophic_Group_3_18005" = "Piscirickettsiaceae__Marine Methylotrophic Group 3_18005",
                                         "Piscirickettsiaceae__Marine_Methylotrophic_Group_3_18003" = "Piscirickettsiaceae__Marine Methylotrophic Group 3_18003",
                                         "Simkaniaceae__Candidatus_Fritschea_892" = "Simkaniaceae__Candidatus Fritschea_892",
                                         "Flavobacteriaceae__Polaribacter_3_52079" = "Flavobacteriaceae __Polaribacter 3_52079",
                                         "Halieaceae__OM60(NOR5)_clade _ 44023" = "Halieaceae__OM60(NOR5) clade_44023",
                                         "Flavobacteriaceae__NS5_marine_group _ 17409" = "Flavobacteriaceae__NS5 marine group_17409",
                                         "Flammeovirgaceae__Candidatus_Amoebophilus_17904" = "Flammeovirgaceae __Candidatus Amoebophilus_17904",
                                         "Halieaceae__OM60(NOR5)_clade_44023" = "Halieaceae__OM60(NOR5) clade_44023",
                                         "Flavobacteriaceae__NS5_marine_group_17409" = "Flavobacteriaceae __NS5 marine group_17409"
                                         ))

### remove doubleunderlines and spaces from labels ###
multipatt_top_10$lowest_tax_level2 <- gsub("__", "_",
multipatt_top_10$lowest_tax_level2) 

multipatt_top_10 <- multipatt_top_10 %>% 
  dplyr::select(-c(relat_abund_host_region, Abundance, Core, Host, Region, lowest_tax_level)) %>% 
  distinct() # this will remove any duplicate OTUs

multipatt_top_10$OTU <- as.character(multipatt_top_10$OTU)
```

## load fasta file sequences ##
```{r}
fasta <-readDNAStringSet("data/NODE-REPRESENTATIVES.DOWNSTREAM.fasta")
OTU <- names(fasta)
sequence <- paste(fasta)
df_sequences <- data.frame(OTU, sequence)
df_sequences$OTU <- as.character(df_sequences$OTU)
```

## combine sequences of fasta file with indval taxonomy table ##
```{r}
Table_S4 <- inner_join(multipatt_top_10, df_sequences, by = "OTU")
write.csv(Table_S4, "data/TableS4.csv", row.names = FALSE)
```